# Generated by Django 4.2.22 on 2025-06-11 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('login', models.CharField(max_length=255, verbose_name='login')),
                ('password', models.TextField(verbose_name='password')),
                ('salt', models.CharField(max_length=200, verbose_name='salt')),
                ('firstName', models.CharField(max_length=255, verbose_name='first_name')),
                ('lastName', models.CharField(max_length=255, verbose_name='last_name')),
                ('pathronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='pathronymic')),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid phone number', regex='^[\\+]?\\d{1,4}[-.\\s]?\\(?\\d{1,3}?\\(?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]\\d{4,9}')], verbose_name='phone_number')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': ('clients',),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.FloatField(default=1.0, verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='image')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('dateEdited', models.DateTimeField(auto_now=True, verbose_name='date_edited')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('deliveryAddress', models.TextField(verbose_name='delivery_address')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='amount_good')),
                ('discount', models.FloatField(default=0.0, verbose_name='discount_per_unit')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.goods', verbose_name='good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order_good',
                'verbose_name_plural': 'order_goods',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(to='routing_app.tag', verbose_name='tags'),
        ),
    ]
