# Generated by Django 4.2.22 on 2025-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routing_app/static/image/%Y/%m/%d', verbose_name='image'),
        ),
    ]
