# Generated by Django 4.2.22 on 2025-06-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing_app', '0002_alter_goods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='image'),
        ),
    ]
