# Generated by Django 4.2.22 on 2025-06-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing_app', '0003_alter_goods_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='amount_good')),
                ('discount', models.FloatField(default=0.0, verbose_name='discount_per_unit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.client', verbose_name='client')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.goods', verbose_name='good')),
            ],
            options={
                'verbose_name': 'basket_goods',
                'verbose_name_plural': 'basket_goods',
            },
        ),
    ]
