# Generated by Django 4.2.22 on 2025-06-16 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing_app', '0004_basketgoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pathronymic',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid phone number', regex='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}')], verbose_name='email_address'),
        ),
        migrations.CreateModel(
            name='FavoriteGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.client', verbose_name='client')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing_app.goods', verbose_name='good')),
            ],
            options={
                'verbose_name': 'favorite_goods',
                'verbose_name_plural': 'favorites_goods',
            },
        ),
    ]
